### ISSUE TITLE
Unexpected Closure

### ISSUE THREAD

**Issue by Sirliamtron** [pekempy/Breeze#11]
Unexpected closure when adding new games, this only occurred after I had already added 5 games. Almost every time I would add a game where title, file path, icon, poster and banner were all inputted the application would close. When reopened the added game would be there.  

Issue reproduced 21 times.

**Comment by pekempy** [comment]
Potentially solved, but is linked to moving files. Will double check at later date

**Comment by pekempy** [comment]
OK this is solved in f229beb
