### ISSUE TITLE
Renaming Entries 

### ISSUE THREAD

**Issue by Sirliamtron** [pekempy/Breeze#13]
When renaming a game entry, application closes. This is due to files still having the previous name in /img/ and /shortcuts/ 
Example renaming test to test1 throws the below:

System.IO.FileNotFoundException: 'Could not find file 

'C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test1-icon.png'
'C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test1-poster.png'
'C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test1-banner.png'
'C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/shortcuts/test1.lnk'.'

Temp workaround is to manually rename the files in /img/ and /shortcuts/

**Comment by pekempy** [comment]
Fixed in 4fbf423
