### ISSUE TITLE
File paths not updating when renaming game entries

### ISSUE THREAD

**Issue by Sirliamtron** [pekempy/Breeze#14]
Added a new game entry:
_Title: test
Path to file: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/shortcuts/test.lnk
Genre(s): Action
Web link: Google.com
Icon: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-icon.png
Poster: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-poster.png
Banner: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-banner.png_

Restarted application
Changed title from ‘test’ to ‘test1’ 
Checked file paths in ‘Edit an existing game’:

_Title: test1
Path to file: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/shortcuts/test.lnk
Genre(s): Action
Web link: Google.com
Icon: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-icon.png
Poster: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-poster.png
Banner: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-banner.png_

Checked /img/, /shortcuts/ & /working/ and all corresponding files have all been renamed to ‘test1’ 
Attempted to run game - successful. (Not sure how this was successful as this was trying to run ‘test.Ink’ and this file no longer existed, it had been changed to ‘test1.Ink’)

Restarted application 
‘Test1’ now has no image when viewing in poster, icon or banner view. 
Checked file paths in ‘Edit an existing game’:

Title: test1
_Path to file: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/shortcuts/test.lnk
Genre(s): Action
Web link: Google.com
Icon: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-icon.png
Poster: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-poster.png
Banner: C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/img/test-banner.png_

Attempted to run game - Unsuccessful 
Application closed
_System.ComponentModel.Win32Exception: 'The system cannot find the file specified'
"C:/Users/Liam/source/repos/Breeze-master/bin/Debug/Resources/working/test.lnk"_

Restarted application
Attempted to change the file paths for icon, poster & banner to the ‘test1’ files in /img/
Received error:
_‘A game with this title already exists. If you need to fix capitalisation, add a character, save and then edit again (Sorry)’_ 

Restarted application
Attempted to change file path for the .exe to the ‘test1’ file in /shortcuts/
Application closed
_System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'_

Restarted application
Attempted to change file path for the .exe to the original .exe selected when creating ‘test’ 
Received error 
_‘A game with this title already exists. If you need to fix capitalisation, add a character, save and then edit again (Sorry)’_ 

‘A game with this title already exists. If you need to fix capitalisation, add a character, save and then edit again (Sorry)’  error generates as there is already a file named ‘test1’ in the appropriate folder (/img/, /shortcuts/, /working/) which was created when the game entry title was changed to ‘test1’ originally. 

Whilst the files were changed to ‘test1’ the file paths continued to try to locate the files ‘test’ after the title change.

**Comment by pekempy** [comment]
Resolved in 2bb61dc
